[DBZ-2510]: Add more logs
debezium/debezium-incubator pull request #191
Opened 2020-09-09 00:32 UTC by bingqinzhou

Log keyspace, table and column when an error occurs.

2020-09-09 08:47 UTC, gunnarmorling requested changes
Thanks, @bingqinzhou! One comment inline which applies to all the changed code parts essentially. Thanks!

2020-09-09 08:47 UTC, gunnarmorling commented on debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java
> +                LOGGER.error("Failed to populate Column {} with Type {} of Table {} in KeySpace {}.",
Let's better either log _or_ rethrow, but not both at the same time, as it'll clutter log files. So I'd suggest to wrap the original exception in a `DebeziumException`, adding the message with the additional context you'd like to propagate. It'll all be logged at once then.

2020-09-12 09:43 UTC, gunnarmorling commented
@bingqinzhou, LGTM now. Could you only squash everything into one commit and rebase it to the current master (in general, let's work with rebases over merges for the sake of a linear and thus cleaner history)? Thanks!

2020-09-14 13:20 UTC, gunnarmorling commented
@bingqinzhou, one more question actually: why is DBZ-2498 reverted here?

2020-09-15 21:05 UTC, bingqinzhou commented
> @bingqinzhou, one more question actually: why is DBZ-2498 reverted here?

Not sure, it seems that 462a5f4, 869b513, 8efe8bc, 7428150 are actually commits from #190 instead of this one. The commit history in my local master seems be messed up, I'm deleting this PR and created #193 with a cleaner commit history.

2020-09-16 07:48 UTC, gunnarmorling commented
Gotcha, no worries. Merged #193 and will close this one. Thanks, @bingqinzhou!

2020-09-16 07:48 UTC, closed without merging